EmailLamba:
        Type: AWS::Serverless::Function
        Properties:
          Architectures:
            - arm64
          Runtime: python3.9
          CodeUri: ./email-lambda/
          Handler: email-lambda.email_handler
          Description: Python Email Lambda
          FunctionName: email-lambda
		  Policies:
            - Statement:
                - Effect: Allow
                  Action:
                    - "ses:SendEmail"
                    - "ses:SendTemplatedEmail"
                    - "ses:SendRawEmail"
                    - "ses:SendBulkTemplatedEmail"
                  Resource: "*"
           Environment:
            Variables:
              SES_CONFIG_SET_NAME:
                Ref: SESConfigSet